### ISSUE TITLE
virtualenv requires Python '!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,>=2.7' but the running Python is 2.6.9

### ISSUE THREAD

**Issue by pcahyna** [linux-system-roles/template#16]
using the template recently I got the error above: https://travis-ci.org/github/linux-system-roles/timesync/jobs/667191881
We should not drop Python 2.6 support though, we need to test it for RHEL 6. Can we lock virtualenv to a version that supported Python 2.6? IIRC this used to work.

**Comment by richm** [comment]
> using the template recently I got the error above: https://travis-ci.org/github/linux-system-roles/timesync/jobs/667191881
> We should not drop Python 2.6 support though, we need to test it for RHEL 6. Can we lock virtualenv to a version that supported Python 2.6? IIRC this used to work.

Because we don't explicitly specify versions of components for pip installs, we get the latest versions of everything.  So when a new component is released and pushed to pypi, we will use it, even though it may not work with some of the older components we use.  This is similar to what happened to us recently with molecule, when we started using molecule v3 all of a sudden and had to lockdown the version of molecule to `molecule<3`.  Not sure, but it looks like the problem is with the version of `virtualenv` - we might have to lockdown the version, but that is being pulled in by `tox`, so we may have to lockdown the version of `tox` too . . .

**Comment by pcahyna** [comment]
It appears that support for Python 2.6 was dropped almost two years ago: https://virtualenv.pypa.io/en/legacy/changes.html#v16-0-0-2018-05-16 . Why didn't we seen the problem though? https://virtualenv.pypa.io/en/legacy/changes.html#v16-7-10-2020-02-24 says that the code to print the error on Python 2.6 was broken on Python 2.6, but this should not have caused the code to work.

**Comment by pcahyna** [comment]
This test for network used python26 and it passed. https://travis-ci.com/github/linux-system-roles/network/jobs/301400301

**Comment by richm** [comment]
From the network role job that works:
```
Collecting virtualenv>=1.11.2; python_version != "3.2" (from tox)
...
  Downloading https://files.pythonhosted.org/packages/ed/ea/e20b5cbebf45d3096e8138ab74eda139595d827677f38e9dd543e6015bdf/virtualenv-15.2.0-py2.py3-none-any.whl (2.6MB)

    100% |████████████████████████████████| 2.6MB 583kB/s 
```
So for some reason it works and pulls in virtualenv 15.2.

Here is the one that fails:
```
Collecting virtualenv>=1.11.2; python_version != "3.2" (from tox)
...
  Downloading https://files.pythonhosted.org/packages/90/9a/d5b295801f94bbc8c6e575563b87ae38dc2ebeb52f93cc4c070ab3836fe8/virtualenv-20.0.14-py2.py3-none-any.whl (4.6MB)

    100% |████████████████████████████████| 4.6MB 335kB/s 

virtualenv requires Python '!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,>=2.7' but the running Python is 2.6.9
```
So why does `pip install tox tox-travis` for the network role pull in `virtualenv 15.2`, but for the template it pulls in `virtualenv 20.0`????

**Comment by richm** [comment]
@pcahyna My latest template PR https://github.com/linux-system-roles/template/pull/18 fixes some issues I ran into with python 2.6 - in my case it was installing ansible 2.6 on python 2.6 - these changes seem necessary for it to work: https://github.com/linux-system-roles/template/pull/18/files#diff-558f916522e7a8ac4ab6f1243c347bf3R23 and https://github.com/linux-system-roles/template/pull/18/files#diff-558f916522e7a8ac4ab6f1243c347bf3R23 and https://github.com/linux-system-roles/template/pull/18/files#diff-558f916522e7a8ac4ab6f1243c347bf3R23

at any rate, please try to reproduce with https://github.com/linux-system-roles/template/pull/18 - for timesync, I have submitted a PR which uses this template: https://github.com/linux-system-roles/timesync/pull/67

**Comment by pcahyna** [comment]
@richm why to worry about Ansible 2.6? It is not supported anymore. We support 2.7, 2.8, 2.9.

**Comment by richm** [comment]
> @richm why to worry about Ansible 2.6? It is not supported anymore. We support 2.7, 2.8, 2.9.

https://github.com/linux-system-roles/template/blob/master/.travis.yml#L11
```yaml
matrix:
  include:
    - python: 2.6
      dist: trusty
```
@pcahyna do you want to drop this?

**Comment by pcahyna** [comment]
@richm why? We need python 2.6. Or is there a better way to install it now?

**Comment by richm** [comment]
> @richm why? We need python 2.6. Or is there a better way to install it now?

Why do we need python 2.6?

**Comment by pcahyna** [comment]
For RHEL 6 support.

**Comment by pcahyna** [comment]
Concerning the subject of the issue, I see that job https://travis-ci.org/github/linux-system-roles/timesync/jobs/669938282 for https://github.com/linux-system-roles/timesync/pull/67 now does
```
Collecting virtualenv>=1.11.2; python_version != "3.2" (from tox)

/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.

  InsecurePlatformWarning

  Downloading https://files.pythonhosted.org/packages/ed/ea/e20b5cbebf45d3096e8138ab74eda139595d827677f38e9dd543e6015bdf/virtualenv-15.2.0-py2.py3-none-any.whl (2.6MB)

    100% |████████████████████████████████| 2.6MB 616kB/s 
```
I.e. it does isntall a sufficiently old virtualenv and it succeeds. I consider the issue fixed (not sure how did it happen, though) and will reopen it if the problem reappears.
