### ISSUE TITLE
Best practices/linting rule for single blank line before each task

### ISSUE THREAD

**Issue by Jakuje** [linux-system-roles/template#58]
As discussed in one crypto policies PR, this is considered a best practice, but not explicitly mentioned anywhere and there is no enforcement in linting tools, making it manual work to enforce this and hard for new contributors.

We should try to create some linting rule for this and mention this in the best practices to ensure better readability of the roles code, tests and playbooks.

https://github.com/linux-system-roles/crypto_policies/pull/3#discussion_r548102917

**Comment by richm** [comment]
This stuff has been moved to tox-lsr - https://github.com/linux-system-roles/tox-lsr/issues/8
