### ISSUE TITLE
To quote stringts or not to quote

### ISSUE THREAD

**Issue by Tronde** [linux-system-roles/template#81]
Looking at files like `defaults/main.yml` and `vars/main.yml`, I see that strings are being quoted there. When working on another role @richm [suggested to me](https://github.com/Tronde/pam_pwd/issues/1) that strings don't need to be quoted. Now I'm a little bit confused.

Looking at the template I would assume that's fine to quote strings. If that's not the case, the quotes should be removed from the var files in the template (I could volunteer to do that). But which way is correct? Please tell me if we have to quote or not to quote strings.

**Comment by nhosoi** [comment]
I've approved https://github.com/linux-system-roles/template/pull/83.

BTW, there are plenty of quoted strings in the existing roles, e.g.,
https://github.com/linux-system-roles/logging/blob/master/roles/rsyslog/vars/main.yml ...
Do we want to clean them up (some day)? Or would the good practices be applied to the new codes only?

**Comment by richm** [comment]
> I've approved #83.
> 
> BTW, there are plenty of quoted strings in the existing roles, e.g., https://github.com/linux-system-roles/logging/blob/master/roles/rsyslog/vars/main.yml ... Do we want to clean them up (some day)? Or would the good practices be applied to the new codes only?

I would say that it isn't necessary to remove quoted strings just for the sake of it.  However, if you are working on some code for some other reason that uses quoted strings unnecessarily, it is probably good to clean that up as part of the unrelated fix.

Note that system roles code in general probably violates https://github.com/redhat-cop/automation-good-practices in several places - this is just one small part of that.

What I would really like to see is tooling around these practices e.g. you could run yamllint or ansible-lint and it would complain about unnecessarily quoted strings.  It's too difficult to enforce all of these manually.

**Comment by nhosoi** [comment]
> What I would really like to see is tooling around these practices e.g. you could run yamllint or ansible-lint and it would complain about unnecessarily quoted strings. It's too difficult to enforce all of these manually.

+100 - it'd be really nice if yamllint/ansible-lint gets smarter and smarter to tell us what to do.
